### ISSUE TITLE
No source code for API ?

### ISSUE THREAD

**Issue by fsfIndravi** [TradingToolCrypto/MT5-RobotFrameWork#1]
Hi ?

Where is source code for API ? You hide it ?

You think this'll help to earn more money with it ? )))

Please share source code for the API! This is not something you should hide from other coders, I can tell you that!

I can simply write this API by my own - just see that you already have an edge in this but just hiding from others! )))

Please share API source code!!!

Regards, 
Alex

**Comment by TradingToolCrypto** [comment]
Source code for the api https://github.com/TradingToolCrypto/MT5-TradingToolCrypto/tree/master/MQL5/Include/TradingToolCrypto

**Comment by TradingToolCrypto** [comment]
Only the exchange libraries are compiled : https://github.com/TradingToolCrypto/MT5-TradingToolCrypto/tree/master/MQL5/Libraries
